### ISSUE TITLE
Locris nigrolimbata - valid species?

### ISSUE THREAD

**Issue by sjl197** [sfg-taxonpages/hoppers#1]
Bouteille et al. 2021
Elevated Locris johannae var. nigrolimbata Lallemand, 1910 to L. nigrolimbata comb. nov.

https://zookeys.pensoft.net/article/58733/

**Comment by proceps** [comment]
@sjl197 thank you for the comment. The record was updated:
https://hoppers.speciesfile.org/otus/3595/overview
