### ISSUE TITLE
Wrong information on Hecalus apicalis (Matsumura, 1912)

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#10]
The orginal combination of [Hecalus apicalis (Matsumura, 1912)](https://hoppers.speciesfile.org/otus/32544/overview) is wrong since its original genus is Parabolocratus. Refer to http://dmitriev.speciesfile.org/taxahelp.asp?hc=139439&key=Erythroneura&lng=En
Idiocerus apicalis Matsumura, 1912 is a separate species.

Please check and correct it.

**Comment by proceps** [comment]
@onegunah 
Thank you for your comment

dmitriev.species.file website is out of data. The database was converted to TaxonWorks 6 years ago. Please use https://hoppers.speciesfile.org for future references.

Hecalus apicalis may refer to three different species:
https://hoppers.speciesfile.org/otus/25659/overview
https://hoppers.speciesfile.org/otus/32544/overview
https://hoppers.speciesfile.org/otus/25831/overview

**Comment by onegunah** [comment]
Then, the current combination of https://hoppers.speciesfile.org/otus/32544/overview seems wrong. Hecalus apicalis (Matsumura, 1912) in Suman et. al (2022), p. 103, may refer to Thomsonia apicalis (Matsumura, 1912). Recent information on Idiocerus aplcalis Matsumura, 1912 is [here](https://zookeys.pensoft.net/article/76731/).

**Comment by proceps** [comment]
Thank you. Yes, a subsequent combination was added to incorrect species. I believe it should be fixed now.

**Comment by onegunah** [comment]
You're welcome!
