### ISSUE TITLE
Typographical error in https://hoppers.speciesfile.org/otus/26909/overview

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#11]
https://hoppers.speciesfile.org/otus/26909/overview
Nomenclature references (1)
Webb, M.D. (1986a) Sugar cane cicadellids of the genus yamototettix (Homoptera: Auchenorrhyncha). Journal of Natural History, 20(1), 131–141.

"yamototettix" should be "Yamatotettix", i.e., "mo" should be corrected into "ma", and "y" should be capitalized.

**Comment by proceps** [comment]
I believe it was OCR error. It should be fixed now. Thank you.
