### ISSUE TITLE
wrong images

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#15]
https://hoppers.speciesfile.org/otus/25100/overview
The above page for _Roxasella biarcuata_ incorrectly includes images of _Roxasella camusi_.
Refer to Zhang, Y.-L. & Webb, M.D. (1996a) A revised classification of the Asian and Pacific selenocephaline leafhoppers (Homoptera: Cicadellidae). _Bulletin of the British Museum (Natural History) Entomology_, 65, 1–103.

**Comment by proceps** [comment]
Fixed, thank you.
