### ISSUE TITLE
incorrect images

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#18]
1. https://hoppers.speciesfile.org/otus/23890/overview
- I think some of the images including the figure of head are incorrect. The image of the head may be those of _Endria nebulosa_ (https://hoppers.speciesfile.org/otus/24167/overview) or near. Please check the relevant paper. (I have no copy of the paper. Would you send me a copy if possible? (onegunah at naver dot com)).

2. https://hoppers.speciesfile.org/otus/24132/overview
The images (of D. tricuspis) should be moved into https://hoppers.speciesfile.org/otus/23890/overview

**Comment by proceps** [comment]
image of the head, it is how it is labeled in the publication. D. tricuspis is moved to proper OTU.
