### ISSUE TITLE
wrong image source

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#21]
https://hoppers.speciesfile.org/otus/24378/overview
& all _Maiestas_ species described by Zhang, Y.-L. & Duan, Y.-N. (2011a) Review of the Deltocephalus group of leafhoppers (Hemiptera: Cicadellidae: Deltocephalinae) in China. Zootaxa, 2870, 1–47.

The image source is incorrectly given as Zhang, B. (2011a) Revision of the leafhopper genus Onukigallia Ishihara, 1955 (Hemiptera: Cicadellidae: Megophthalminae). Zootaxa, 2915, 52–60.

**Comment by onegunah** [comment]
Would you send me a copy of Zhang, Y.-L. & Duan, Y.-N. (2011a)? I don't have one.
Review of the Deltocephalus group of leafhoppers (Hemiptera: Cicadellidae: Deltocephalinae) in China. Zootaxa, 2870, 1–47.

**Comment by proceps** [comment]
fixed
