### ISSUE TITLE
error in reference

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#22]
https://hoppers.speciesfile.org/otus/38255/overview
Nomenclature references
Distant, W.L. (1907g) Contributions to a knowledge of the Ledrinae. Bulletin et Annales de la Société Entomologique de Belgique, 58, 185–197.

The journal name and volume number should be changed into "Annales de la Société entomologique de Belgique, 51".

**Comment by proceps** [comment]
Thank you. The record is updated.
