### ISSUE TITLE
possible incorrect images

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#23]
https://hoppers.speciesfile.org/otus/45620/overview

At least one of two color images from Song & Li (2014) are probably incorrect, and possibly both are incorrect. Please check the related material. I don't have the book.

**Comment by proceps** [comment]
both are marked as Motaga rokfa on color plates. I could not find any references to the color plates in the text, only line drawings are referenced. Both images do not make much sense. Deleted both.
