### ISSUE TITLE
Incorrect distribution?

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#29]
https://hoppers.speciesfile.org/otus/45648/overview

It's definitely a New Worold species. But the distribution only includes India.

**Comment by proceps** [comment]
India delete as a distribution. The correct distribution will be entered shortly

**Comment by onegunah** [comment]
The distribution in the genus page (https://hoppers.speciesfile.org/otus/45647/overview) should be also corrected.

**Comment by proceps** [comment]
The distribution of higher taxa is assembled from individual species records. It takes longer time to update. It should automatically change in few days.
