### ISSUE TITLE
mismatch between images

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#31]
https://hoppers.speciesfile.org/otus/31521/overview

The color photos do not match with the black and white illustration (4th image). It seems that the color photos are closer to the genus _Minucella_ than _Cyrta_. Would you check the images?

**Comment by proceps** [comment]
Photos belong to the type specimen. Black and white illustration is also for the type specimen from the original publication. The photos also come with the type label, so it should be the holotype specimen.
