### ISSUE TITLE
Synonymy?

### ISSUE THREAD

**Issue by onegunah** [sfg-taxonpages/hoppers#32]
https://hoppers.speciesfile.org/otus/29799/overview

_Penthimia scapularis_ was synonymized with _Penthimia compacta_ (https://hoppers.speciesfile.org/otus/29691/overview) by Shobharani et al., 2018.
(Shobharani, M., Viraktamath, C.A. & Webb, M.D. (2018) Review of the leafhopper genus Penthimia Germar (Hemiptera: Cicadellidae: Deltocephalinae) from the Indian subcontinent with description of seven new species. Zootaxa, 4369(1), 1–45. https://doi.org/10.11646/zootaxa.4369.1.1)

**Comment by proceps** [comment]
The statement from the paper: "Three species are treated in a new Penthimia
compacta Walker complex, i.e., Penthimia compacta Walker 1851, Penthimia subniger Distant 1908 and Penthimia
scapularis Distant 1908"
No synonymy is proposed.

**Comment by onegunah** [comment]
OK! I missed the word "complex".
