### ISSUE TITLE
Psalmocharia querulus

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/hoppers#7]
https://hoppers.speciesfile.org/otus/8680/overview is querula throughout the literature....who corrected querulus?

**Comment by proceps** [comment]
'querulus' is Latin adjective https://en.wiktionary.org/wiki/querulus
Psalmocharias is a masculine genus name. TaxonWorks automatically match proper ending of the specific epithet with the gender of the genus. Originally the species was described in the genus 'Cicada', probably the current combination was never published.

**Comment by klausriede** [comment]
hmm - so we have a nomenclatural act by AI taxonworks? I wonder if this is valid. In any case it is confusing

**Comment by proceps** [comment]
New combinations, new synonymy, corrections of spellings are not nomenclatural acts in ICZN sense. Those do not require publication and could be implemented directly in the DB. For example, somebody publish a statement that a genus B is a synonym of the genus A, but no new explicit combinations mentioned in the paper, as a curator, I can still transfer all the species from one genus to another, although the combinations were never published. There is no much of AI behind, in all cases it is still a curatorial decision.

**Comment by klausriede** [comment]
agreed, except for the epithet. For sake of name stability the epithet should remain as it is , in this case widely in the literature see http://treatment.plazi.org/id/A82F87957F12FFE0FF3E5C69FA83F9D9

**Comment by klausriede** [comment]
agreed, but the name P querula is widely spread in the literature https://zenodo.org/records/5984881 so it should appear somewhere in the database

**Comment by proceps** [comment]
Please look at the Nomenclature section, all name usages are listed there. You can see also references in CoL (https://www.catalogueoflife.org/data/taxon/4NB3L) and GBIF (https://www.gbif.org/species/8141211)
