### ISSUE TITLE
P plagifer never seen in France

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/hoppers#8]
https://www.inaturalist.org/observations?place_id=any&subview=map&taxon_id=740260
...in contrast to the map we see here
https://hoppers.speciesfile.org/otus/8679/overview

**Comment by proceps** [comment]
I removed the species from France. Although, it was reported in the the country in Nast's catalogue and after repeated in Sanborn's catalogue. In Nast it is reported as questionable.

**Comment by klausriede** [comment]
Would be interesting to see/track these geographic references somewhere. F.e. when you click on France find the reference why France has been marked up

**Comment by proceps** [comment]
It could be a good addition. At the moment, you can download DwC file and get detailed information.
