### ISSUE TITLE
Microsargini is still under Aphrophorinae and more

### ISSUE THREAD

**Issue by Miudod2n** [sfg-taxonpages/hoppers#9]
Hamilton, K.G.A. (2016a) Neotropical spittlebugs related to Neaenini (Hemiptera, Cercopidae) and the origins of subfamily Cercopinae. Zootaxa, 4169(2), 201–250. 

Is referenced but the tribe continues under the wrong sub-fam.

The other taxonomy actions in that paper are also not reflected in the database. The list is too long to post here.

**Comment by proceps** [comment]
The classification in the DB follows the recently published comprehansive classification of Cercopidae:
Crispolon, E.S., Jr., Soulier-Perkins, A. & Guilbert, E. (2023) Molecular phylogeny of Cercopidae (Hemiptera, Cercopoidea). Zoologica Scripta, 52(5), 494–516. https://doi.org/10.1111/zsc.12597
Citations to Hamilton's classification are being added to the DB.
